development:
  adapter: mysql2
  encoding: utf8
  database: acme_development
  username: root
  password:
  host: localhost
  port: 3000

test:
  adapter: mysql2
  encoding: utf8
  database: acme_test
  username: root
  password: celtics
  host:
  port: 3000
