development:
  adapter: mysql2
  encoding: utf8
  database: acme_development
  username: <%= ENV['mysql_user'] %>
  password: <%= ENV['mysql_password'] %>
  host: localhost
  port: 3000

test:
  adapter: mysql2
  encoding: utf8
  database: acme_test
  username: <%= ENV['mysql_user'] %>
  password: <%= ENV['mysql_password'] %>
  host: localhost
  port: 3000
